name: Release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: tensr-linux
            asset_name: tensr-linux-x64.tar.gz
            platform: Linux x64
          - os: windows-latest
            artifact_name: tensr-windows
            asset_name: tensr-windows-x64.zip
            platform: Windows x64
          - os: macos-latest
            artifact_name: tensr-macos
            asset_name: tensr-macos-x64.tar.gz
            platform: macOS x64
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Build Release (xmake)
      run: |
        xmake config -m release
        xmake build tensr
    
    - name: Build Release (CMake)
      run: |
        cmake -B build-cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build build-cmake --config Release
    
    - name: Package (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        mkdir -p release/lib
        mkdir -p release/include
        mkdir -p release/examples
        cp -r include/* release/include/
        cp -r examples/* release/examples/ || true
        cp xmake.lua release/
        cp CMakeLists.txt release/
        cp LICENSE release/
        cp README.md release/
        find build -name "libtensr.a" -exec cp {} release/lib/ \; || true
        find build-cmake -name "libtensr.a" -exec cp {} release/lib/ \; || true
        tar -czf ${{ matrix.asset_name }} -C release .
    
    - name: Package (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        New-Item -ItemType Directory -Force -Path release\lib
        New-Item -ItemType Directory -Force -Path release\include
        New-Item -ItemType Directory -Force -Path release\examples
        Copy-Item -Recurse -Force include\* release\include\
        Copy-Item -Recurse -Force examples\* release\examples\ -ErrorAction SilentlyContinue
        Copy-Item xmake.lua release\
        Copy-Item CMakeLists.txt release\
        Copy-Item LICENSE release\
        Copy-Item README.md release\
        Get-ChildItem -Path build -Recurse -Filter tensr.lib -ErrorAction SilentlyContinue | Copy-Item -Destination release\lib\
        Get-ChildItem -Path build-cmake -Recurse -Filter tensr.lib -ErrorAction SilentlyContinue | Copy-Item -Destination release\lib\
    
    - name: Compress (Windows)
      if: runner.os == 'Windows'
      run: Compress-Archive -Path release\* -DestinationPath ${{ matrix.asset_name }}
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./${{ matrix.asset_name }}
        token: ${{ secrets.GH_TOKEN }}

  publish-conan:
    name: Publish Conan Package
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    
    - name: Install xmake
      run: |
        curl -fsSL https://xmake.io/shget.text | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install Conan
      run: |
        pip install conan
        conan profile detect --force
    
    - name: Create Conan Package
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        conan create . --version=${{ github.event.release.tag_name }}
    
    - name: Package Conan Recipe
      run: |
        mkdir -p conan-package
        cp conanfile.py conan-package/
        cp xmake.lua conan-package/
        cp CMakeLists.txt conan-package/
        cp LICENSE conan-package/
        cp README.md conan-package/
        cp -r include conan-package/
        cp -r src conan-package/
        cp -r examples conan-package/ || true
        tar -czf tensr-conan-${{ github.event.release.tag_name }}.tar.gz -C conan-package .
    
    - name: Upload Conan Package to Release
      uses: softprops/action-gh-release@v2
      with:
        files: tensr-conan-${{ github.event.release.tag_name }}.tar.gz
        token: ${{ secrets.GH_TOKEN }}

  publish-xmake:
    name: Publish xmake Package
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Install xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    
    - name: Build and Package
      run: |
        xmake config -m release
        xmake build
        xmake package
    
    - name: Create xmake Package
      run: |
        mkdir -p xmake-package
        cp xmake.lua xmake-package/
        cp CMakeLists.txt xmake-package/
        cp LICENSE xmake-package/
        cp README.md xmake-package/
        cp -r include xmake-package/
        cp -r src xmake-package/
        cp -r examples xmake-package/ || true
        tar -czf tensr-xmake-${{ github.event.release.tag_name }}.tar.gz -C xmake-package .
    
    - name: Upload xmake Package to Release
      uses: softprops/action-gh-release@v2
      with:
        files: tensr-xmake-${{ github.event.release.tag_name }}.tar.gz
        token: ${{ secrets.GH_TOKEN }}

  publish-vcpkg:
    name: Publish vcpkg Port
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Create vcpkg Port
      run: |
        mkdir -p vcpkg-port/ports/tensr
        cp vcpkg.json vcpkg-port/ports/tensr/
        cp xmake.lua vcpkg-port/ports/tensr/
        cp CMakeLists.txt vcpkg-port/ports/tensr/
        cp LICENSE vcpkg-port/ports/tensr/
        cp README.md vcpkg-port/ports/tensr/
        cp -r include vcpkg-port/ports/tensr/
        cp -r src vcpkg-port/ports/tensr/
        cp -r examples vcpkg-port/ports/tensr/ || true
        cat > vcpkg-port/ports/tensr/portfile.cmake << 'EOF'
        vcpkg_from_github(
            OUT_SOURCE_PATH SOURCE_PATH
            REPO muhammad-fiaz/tensr
            REF ${{ github.event.release.tag_name }}
            SHA512 0
            HEAD_REF main
        )
        
        vcpkg_configure_cmake(
            SOURCE_PATH ${SOURCE_PATH}
            PREFER_NINJA
        )
        
        vcpkg_install_cmake()
        vcpkg_fixup_cmake_targets()
        
        file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
        file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/tensr RENAME copyright)
        EOF
    
    - name: Package vcpkg Port
      run: |
        tar -czf tensr-vcpkg-${{ github.event.release.tag_name }}.tar.gz -C vcpkg-port .
    
    - name: Upload vcpkg Port to Release
      uses: softprops/action-gh-release@v2
      with:
        files: tensr-vcpkg-${{ github.event.release.tag_name }}.tar.gz
        token: ${{ secrets.GH_TOKEN }}

  update-release-notes:
    name: Update Release Notes
    runs-on: ubuntu-latest
    needs: [build, publish-xmake, publish-conan, publish-vcpkg]
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Generate Release Notes
      id: notes
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        REPO="${{ github.repository }}"
        
        cat > release_notes.md << EOF
        ## 📦 Installation
        
        | File | Platform | Method | Download |
        |------|----------|--------|----------|
        | \`tensr-linux-x64.tar.gz\` | Linux x64 | Binary | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-linux-x64.tar.gz) |
        | \`tensr-windows-x64.zip\` | Windows x64 | Binary | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-windows-x64.zip) |
        | \`tensr-macos-x64.tar.gz\` | macOS x64 | Binary | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-macos-x64.tar.gz) |
        | \`tensr-xmake-${VERSION}.tar.gz\` | Windows, Linux, macOS | xmake | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-xmake-${VERSION}.tar.gz) |
        | \`tensr-conan-${VERSION}.tar.gz\` | Windows, Linux, macOS | Conan | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-conan-${VERSION}.tar.gz) |
        | \`tensr-vcpkg-${VERSION}.tar.gz\` | Windows, Linux, macOS | vcpkg | [Download](https://github.com/${REPO}/releases/download/${VERSION}/tensr-vcpkg-${VERSION}.tar.gz) |
        
        **Note:** All packages include static libraries (.a/.lib), headers, and xmake.lua for easy integration.
        
        ## 🚀 Quick Install
        
        ### Binary Installation
        
        **Linux/macOS:**
        \`\`\`bash
        wget https://github.com/${REPO}/releases/download/${VERSION}/tensr-linux-x64.tar.gz
        tar -xzf tensr-linux-x64.tar.gz
        sudo cp -r lib/* /usr/local/lib/
        sudo cp -r include/* /usr/local/include/
        \`\`\`
        
        **Windows:**
        Download and extract \`tensr-windows-x64.zip\`, then add to your project paths.
        
        ### xmake
        \`\`\`bash
        wget https://github.com/${REPO}/releases/download/${VERSION}/tensr-xmake-${VERSION}.tar.gz
        tar -xzf tensr-xmake-${VERSION}.tar.gz
        cd tensr-xmake-${VERSION}
        xmake install
        \`\`\`
        
        Or add to your xmake.lua:
        \`\`\`lua
        add_requires("tensr ${VERSION}")
        target("your_app")
            add_packages("tensr")
        \`\`\`
        
        ### Conan
        \`\`\`bash
        wget https://github.com/${REPO}/releases/download/${VERSION}/tensr-conan-${VERSION}.tar.gz
        tar -xzf tensr-conan-${VERSION}.tar.gz
        conan create . --version=${VERSION}
        \`\`\`
        
        ### vcpkg
        \`\`\`bash
        wget https://github.com/${REPO}/releases/download/${VERSION}/tensr-vcpkg-${VERSION}.tar.gz
        tar -xzf tensr-vcpkg-${VERSION}.tar.gz
        cp -r ports/tensr \$VCPKG_ROOT/ports/
        vcpkg install tensr
        \`\`\`
        
        ## 📚 Documentation
        
        Visit [https://muhammad-fiaz.github.io/tensr](https://muhammad-fiaz.github.io/tensr) for full documentation.
        
        ---
        
        **Full Changelog**: https://github.com/${REPO}/commits/${VERSION}
        EOF
        
    - name: Update Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        body_path: release_notes.md
